### ISSUE TITLE
Can I use TeXZilla to insert/render LaTeX formulae into Gmail, as done by TeX-for-Gmail?

### ISSUE THREAD

**Issue by hongyi-zhao** [fred-wang/TeXZilla#74]
I want to know if this tool can let user insert/render LaTeX formulae into Gmail, as done by [TeX-for-Gmail](https://github.com/TeX-for-Gmail/TeX-for-Gmail).

Regards,
HZ

**Comment by hongyi-zhao** [comment]
It seems that [TeX-for-Gmail](https://github.com/TeX-for-Gmail/TeX-for-Gmail) and [TeXZilla](https://github.com/fred-wang/TeXZilla) are based on the same tool set and language. So, I filed this issue.

**Comment by fred-wang** [comment]
TeXZilla is a "Javascript LaTeX-to-MathML converter" so you can use it a Chrome extension (JavaScript) and take LaTeX formulaes as input. The difference with TeX-for-Gmail is the output which uses images (IIUC) instead of MathML. Images are supported my all mail client/server, but that's not necessarily the case for MathML. At worst, you can maybe use something like http://fred-wang.github.io/TeXZilla/examples/toImage.html to generate images...

Closing this issue since this is a work to be done by other projects, not the library itself.
